name: sh_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  auto_route: ^9.3.0+1
  auto_route_generator: ^9.3.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true
  assets: 
  - .env
  - assets/
